name: waybright
description: A library for building wayland compositors.
version: 0.1.0
repository: https://github.com/brighta19/waybright

environment:
  sdk: '>=3.0.0'

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^10.0.0
  lints: ^3.0.0
  test: ^1.21.0

ffigen:
  output: 'lib/src/generated/waybright_bindings.dart'
  name: 'WaybrightLibrary'
  description: 'Bindings from Waybright'
  compiler-opts:
  - '-DWLR_USE_UNSTABLE'
  - '-I/usr/include/pixman-1'
  - '-Ilib/src/native/'
  - '-I/usr/lib/gcc/x86_64-linux-gnu/11/include/'
  headers:
    entry-points:
      - 'lib/src/native/waybright.h'
  functions:
    include:
      - '^waybright_.*'
      - '^wlr_.*'
  structs:
    include:
      - '^waybright_.*'
      - '^wlr_.*'
      - '^pixman_*'
    rename:
      '(.*)': 'struct_$1'
  unions:
    exclude:
      - '.*'
  enums:
    include:
      - '^wb_.*'
      - '^wl_.*'
      - '^wlr_.*'
    rename:
      '(.*)': 'enum_$1'
  unnamed-enums:
    exclude:
      - '.*'
  globals:
    exclude:
      - '.*'
  typedefs:
    exclude:
      - '.*'
  macros:
    exclude:
      - '.*'
