name: waybright
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1

ffigen:
  output: 'lib/src/generated/waybright_bindings.dart'
  name: 'WaybrightLibrary'
  description: 'Bindings from Waybright'
  compiler-opts:
  - '-DWLR_USE_UNSTABLE'
  - '-I/usr/include/pixman-1'
  - '-Ilib/src/native/'
  headers:
    entry-points:
      - 'lib/src/native/waybright.h'
  functions:
    include:
      - '^waybright_.*'
      - '^wlr_.*'
  structs:
    include:
      - '^waybright_.*'
      - '^wlr_.*'
    rename:
      '(.*)': 'struct_$1'
  unions:
    exclude:
      - '.*'
  enums:
    include:
      - '^wb_.*'
      - '^wl_.*'
      - '^wlr_.*'
    rename:
      '(.*)': 'enum_$1'
  unnamed-enums:
    exclude:
      - '.*'
  globals:
    exclude:
      - '.*'
  typedefs:
    exclude:
      - '.*'
  macros:
    exclude:
      - '.*'
