name: waybright
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1

ffigen:
  output: 'lib/waybright_bindings.dart'
  name: 'WaybrightLibrary'
  description: 'Bindings from Waybright'
  compiler-opts:
  - '-DWLR_USE_UNSTABLE'
  headers:
    entry-points:
      - 'src/waybright.h'
  structs:
    rename:
      '(.*)': 'struct_$1'
  enums:
    rename:
      '(.*)': 'enum_$1'
